workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.9

stages:
  - test

before_script:
  - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - pytest app_tests

mypy:
  stage: test
  script:
    - mypy src/

black:
  stage: test
  script:
    - black src/

isort:
  stage: test
  script:
    - isort src/